### ISSUE TITLE
Correct English text in the image

### ISSUE THREAD

**Issue by emartynov** [terrakok/terrakok#1]
Correct would be:

I work *in the* Kotlin team

Reference:
<img width="609" alt="Screenshot 2020-09-04 at 15 02 43" src="https://user-images.githubusercontent.com/295424/92242229-c8029c80-eebf-11ea-9902-1d9c3c022124.png">

**Comment by zoobestik** [comment]
yeah :(

It has been fixed, you can get new banner from generator

**Comment by emartynov** [comment]
No issues at all! Stay positive.
